### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by josuealan2** [josuealan2/prework-study-guide#1]
#HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
Then I see four boxes titles HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by rohit-chaware** [comment]
Hello, How much should be the notes section, can you give initial size of the article associated with the given topic.
